import type { LocationApiSchema } from '@/types/server/location-api';

export const locationsApiFixture: LocationApiSchema[] = [
  {
    id: 1,
    name: 'Earth (C-137)',
    type: 'Planet',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/38',
      'https://rickandmortyapi.com/api/character/45',
      'https://rickandmortyapi.com/api/character/71',
      'https://rickandmortyapi.com/api/character/82',
    ],
    url: 'https://rickandmortyapi.com/api/location/1',
    created: '2017-11-10T12:42:04.162Z',
  },
  {
    id: 2,
    name: 'Abadango',
    type: 'Cluster',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/6'],
    url: 'https://rickandmortyapi.com/api/location/2',
    created: '2017-11-10T13:06:38.182Z',
  },
  {
    id: 3,
    name: 'Citadel of Ricks',
    type: 'Space station',
    dimension: 'unknown',
    residents: ['https://rickandmortyapi.com/api/character/8'],
    url: 'https://rickandmortyapi.com/api/location/3',
    created: '2017-11-10T13:08:13.191Z',
  },
  {
    id: 4,
    name: "Worldender's lair",
    type: 'Planet',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/10',
      'https://rickandmortyapi.com/api/character/81',
      'https://rickandmortyapi.com/api/character/208',
      'https://rickandmortyapi.com/api/character/226',
      'https://rickandmortyapi.com/api/character/340',
      'https://rickandmortyapi.com/api/character/362',
      'https://rickandmortyapi.com/api/character/375',
      'https://rickandmortyapi.com/api/character/382',
      'https://rickandmortyapi.com/api/character/395',
    ],
    url: 'https://rickandmortyapi.com/api/location/4',
    created: '2017-11-10T13:08:20.569Z',
  },
  {
    id: 5,
    name: 'Anatomy Park',
    type: 'Microverse',
    dimension: 'Dimension C-137',
    residents: [
      'https://rickandmortyapi.com/api/character/12',
      'https://rickandmortyapi.com/api/character/17',
      'https://rickandmortyapi.com/api/character/96',
      'https://rickandmortyapi.com/api/character/97',
      'https://rickandmortyapi.com/api/character/98',
      'https://rickandmortyapi.com/api/character/99',
      'https://rickandmortyapi.com/api/character/100',
      'https://rickandmortyapi.com/api/character/101',
      'https://rickandmortyapi.com/api/character/108',
      'https://rickandmortyapi.com/api/character/268',
      'https://rickandmortyapi.com/api/character/300',
    ],
    url: 'https://rickandmortyapi.com/api/location/5',
    created: '2017-11-10T13:08:46.060Z',
  },
  {
    id: 6,
    name: 'Interdimensional Cable',
    type: 'TV',
    dimension: 'unknown',
    residents: [
      'https://rickandmortyapi.com/api/character/20',
      'https://rickandmortyapi.com/api/character/28',
      'https://rickandmortyapi.com/api/character/29',
      'https://rickandmortyapi.com/api/character/34',
      'https://rickandmortyapi.com/api/character/49',
      'https://rickandmortyapi.com/api/character/51',
      'https://rickandmortyapi.com/api/character/54',
      'https://rickandmortyapi.com/api/character/121',
      'https://rickandmortyapi.com/api/character/126',
      'https://rickandmortyapi.com/api/character/129',
      'https://rickandmortyapi.com/api/character/134',
      'https://rickandmortyapi.com/api/character/136',
      'https://rickandmortyapi.com/api/character/145',
      'https://rickandmortyapi.com/api/character/157',
      'https://rickandmortyapi.com/api/character/173',
      'https://rickandmortyapi.com/api/character/184',
      'https://rickandmortyapi.com/api/character/205',
      'https://rickandmortyapi.com/api/character/207',
      'https://rickandmortyapi.com/api/character/214',
      'https://rickandmortyapi.com/api/character/222',
      'https://rickandmortyapi.com/api/character/223',
      'https://rickandmortyapi.com/api/character/224',
      'https://rickandmortyapi.com/api/character/225',
      'https://rickandmortyapi.com/api/character/250',
      'https://rickandmortyapi.com/api/character/254',
      'https://rickandmortyapi.com/api/character/260',
      'https://rickandmortyapi.com/api/character/264',
      'https://rickandmortyapi.com/api/character/266',
      'https://rickandmortyapi.com/api/character/275',
      'https://rickandmortyapi.com/api/character/277',
      'https://rickandmortyapi.com/api/character/279',
      'https://rickandmortyapi.com/api/character/312',
      'https://rickandmortyapi.com/api/character/314',
      'https://rickandmortyapi.com/api/character/315',
      'https://rickandmortyapi.com/api/character/316',
      'https://rickandmortyapi.com/api/character/317',
      'https://rickandmortyapi.com/api/character/318',
      'https://rickandmortyapi.com/api/character/334',
      'https://rickandmortyapi.com/api/character/351',
      'https://rickandmortyapi.com/api/character/358',
      'https://rickandmortyapi.com/api/character/367',
      'https://rickandmortyapi.com/api/character/370',
      'https://rickandmortyapi.com/api/character/373',
      'https://rickandmortyapi.com/api/character/403',
      'https://rickandmortyapi.com/api/character/406',
      'https://rickandmortyapi.com/api/character/407',
      'https://rickandmortyapi.com/api/character/408',
      'https://rickandmortyapi.com/api/character/409',
      'https://rickandmortyapi.com/api/character/410',
      'https://rickandmortyapi.com/api/character/411',
      'https://rickandmortyapi.com/api/character/412',
      'https://rickandmortyapi.com/api/character/413',
      'https://rickandmortyapi.com/api/character/414',
      'https://rickandmortyapi.com/api/character/415',
      'https://rickandmortyapi.com/api/character/416',
      'https://rickandmortyapi.com/api/character/417',
      'https://rickandmortyapi.com/api/character/418',
      'https://rickandmortyapi.com/api/character/457',
      'https://rickandmortyapi.com/api/character/458',
      'https://rickandmortyapi.com/api/character/459',
      'https://rickandmortyapi.com/api/character/709',
      'https://rickandmortyapi.com/api/character/711',
    ],
    url: 'https://rickandmortyapi.com/api/location/6',
    created: '2017-11-10T13:09:09.102Z',
  },
  {
    id: 20,
    name: 'Earth (Replacement Dimension)',
    type: 'Planet',
    dimension: 'Replacement Dimension',
    residents: [
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/9',
      'https://rickandmortyapi.com/api/character/11',
      'https://rickandmortyapi.com/api/character/13',
      'https://rickandmortyapi.com/api/character/16',
      'https://rickandmortyapi.com/api/character/31',
      'https://rickandmortyapi.com/api/character/32',
      'https://rickandmortyapi.com/api/character/50',
      'https://rickandmortyapi.com/api/character/58',
      'https://rickandmortyapi.com/api/character/59',
      'https://rickandmortyapi.com/api/character/64',
      'https://rickandmortyapi.com/api/character/66',
      'https://rickandmortyapi.com/api/character/76',
      'https://rickandmortyapi.com/api/character/88',
      'https://rickandmortyapi.com/api/character/103',
      'https://rickandmortyapi.com/api/character/107',
      'https://rickandmortyapi.com/api/character/109',
      'https://rickandmortyapi.com/api/character/113',
      'https://rickandmortyapi.com/api/character/115',
      'https://rickandmortyapi.com/api/character/124',
      'https://rickandmortyapi.com/api/character/128',
      'https://rickandmortyapi.com/api/character/137',
      'https://rickandmortyapi.com/api/character/138',
      'https://rickandmortyapi.com/api/character/141',
      'https://rickandmortyapi.com/api/character/147',
      'https://rickandmortyapi.com/api/character/149',
      'https://rickandmortyapi.com/api/character/151',
      'https://rickandmortyapi.com/api/character/154',
      'https://rickandmortyapi.com/api/character/166',
      'https://rickandmortyapi.com/api/character/167',
      'https://rickandmortyapi.com/api/character/170',
      'https://rickandmortyapi.com/api/character/171',
      'https://rickandmortyapi.com/api/character/172',
      'https://rickandmortyapi.com/api/character/180',
      'https://rickandmortyapi.com/api/character/181',
      'https://rickandmortyapi.com/api/character/182',
      'https://rickandmortyapi.com/api/character/185',
      'https://rickandmortyapi.com/api/character/189',
      'https://rickandmortyapi.com/api/character/190',
      'https://rickandmortyapi.com/api/character/210',
      'https://rickandmortyapi.com/api/character/217',
      'https://rickandmortyapi.com/api/character/218',
      'https://rickandmortyapi.com/api/character/219',
      'https://rickandmortyapi.com/api/character/227',
      'https://rickandmortyapi.com/api/character/230',
      'https://rickandmortyapi.com/api/character/233',
      'https://rickandmortyapi.com/api/character/234',
      'https://rickandmortyapi.com/api/character/236',
      'https://rickandmortyapi.com/api/character/237',
      'https://rickandmortyapi.com/api/character/240',
      'https://rickandmortyapi.com/api/character/241',
      'https://rickandmortyapi.com/api/character/243',
      'https://rickandmortyapi.com/api/character/244',
      'https://rickandmortyapi.com/api/character/245',
      'https://rickandmortyapi.com/api/character/248',
      'https://rickandmortyapi.com/api/character/251',
      'https://rickandmortyapi.com/api/character/255',
      'https://rickandmortyapi.com/api/character/259',
      'https://rickandmortyapi.com/api/character/262',
      'https://rickandmortyapi.com/api/character/265',
      'https://rickandmortyapi.com/api/character/272',
      'https://rickandmortyapi.com/api/character/276',
      'https://rickandmortyapi.com/api/character/280',
      'https://rickandmortyapi.com/api/character/292',
      'https://rickandmortyapi.com/api/character/293',
      'https://rickandmortyapi.com/api/character/324',
      'https://rickandmortyapi.com/api/character/326',
      'https://rickandmortyapi.com/api/character/327',
      'https://rickandmortyapi.com/api/character/332',
      'https://rickandmortyapi.com/api/character/335',
      'https://rickandmortyapi.com/api/character/341',
      'https://rickandmortyapi.com/api/character/346',
      'https://rickandmortyapi.com/api/character/347',
      'https://rickandmortyapi.com/api/character/352',
      'https://rickandmortyapi.com/api/character/353',
      'https://rickandmortyapi.com/api/character/354',
      'https://rickandmortyapi.com/api/character/357',
      'https://rickandmortyapi.com/api/character/360',
      'https://rickandmortyapi.com/api/character/361',
      'https://rickandmortyapi.com/api/character/363',
      'https://rickandmortyapi.com/api/character/365',
      'https://rickandmortyapi.com/api/character/374',
      'https://rickandmortyapi.com/api/character/377',
      'https://rickandmortyapi.com/api/character/390',
      'https://rickandmortyapi.com/api/character/391',
      'https://rickandmortyapi.com/api/character/401',
      'https://rickandmortyapi.com/api/character/402',
      'https://rickandmortyapi.com/api/character/405',
      'https://rickandmortyapi.com/api/character/423',
      'https://rickandmortyapi.com/api/character/435',
      'https://rickandmortyapi.com/api/character/437',
      'https://rickandmortyapi.com/api/character/438',
      'https://rickandmortyapi.com/api/character/439',
      'https://rickandmortyapi.com/api/character/440',
      'https://rickandmortyapi.com/api/character/452',
      'https://rickandmortyapi.com/api/character/453',
      'https://rickandmortyapi.com/api/character/467',
      'https://rickandmortyapi.com/api/character/468',
      'https://rickandmortyapi.com/api/character/469',
      'https://rickandmortyapi.com/api/character/471',
      'https://rickandmortyapi.com/api/character/492',
      'https://rickandmortyapi.com/api/character/493',
      'https://rickandmortyapi.com/api/character/497',
      'https://rickandmortyapi.com/api/character/509',
      'https://rickandmortyapi.com/api/character/510',
      'https://rickandmortyapi.com/api/character/511',
      'https://rickandmortyapi.com/api/character/512',
      'https://rickandmortyapi.com/api/character/513',
      'https://rickandmortyapi.com/api/character/514',
      'https://rickandmortyapi.com/api/character/516',
      'https://rickandmortyapi.com/api/character/517',
      'https://rickandmortyapi.com/api/character/523',
      'https://rickandmortyapi.com/api/character/524',
      'https://rickandmortyapi.com/api/character/526',
      'https://rickandmortyapi.com/api/character/534',
      'https://rickandmortyapi.com/api/character/535',
      'https://rickandmortyapi.com/api/character/536',
      'https://rickandmortyapi.com/api/character/537',
      'https://rickandmortyapi.com/api/character/538',
      'https://rickandmortyapi.com/api/character/539',
      'https://rickandmortyapi.com/api/character/540',
      'https://rickandmortyapi.com/api/character/541',
      'https://rickandmortyapi.com/api/character/561',
      'https://rickandmortyapi.com/api/character/562',
      'https://rickandmortyapi.com/api/character/564',
      'https://rickandmortyapi.com/api/character/570',
      'https://rickandmortyapi.com/api/character/575',
      'https://rickandmortyapi.com/api/character/584',
      'https://rickandmortyapi.com/api/character/585',
      'https://rickandmortyapi.com/api/character/586',
      'https://rickandmortyapi.com/api/character/588',
      'https://rickandmortyapi.com/api/character/590',
      'https://rickandmortyapi.com/api/character/591',
      'https://rickandmortyapi.com/api/character/592',
      'https://rickandmortyapi.com/api/character/667',
      'https://rickandmortyapi.com/api/character/672',
      'https://rickandmortyapi.com/api/character/680',
      'https://rickandmortyapi.com/api/character/684',
      'https://rickandmortyapi.com/api/character/686',
      'https://rickandmortyapi.com/api/character/687',
      'https://rickandmortyapi.com/api/character/688',
      'https://rickandmortyapi.com/api/character/689',
      'https://rickandmortyapi.com/api/character/690',
      'https://rickandmortyapi.com/api/character/691',
      'https://rickandmortyapi.com/api/character/692',
      'https://rickandmortyapi.com/api/character/693',
      'https://rickandmortyapi.com/api/character/694',
      'https://rickandmortyapi.com/api/character/695',
      'https://rickandmortyapi.com/api/character/696',
      'https://rickandmortyapi.com/api/character/697',
      'https://rickandmortyapi.com/api/character/698',
      'https://rickandmortyapi.com/api/character/699',
      'https://rickandmortyapi.com/api/character/700',
      'https://rickandmortyapi.com/api/character/701',
      'https://rickandmortyapi.com/api/character/702',
      'https://rickandmortyapi.com/api/character/703',
      'https://rickandmortyapi.com/api/character/704',
      'https://rickandmortyapi.com/api/character/705',
      'https://rickandmortyapi.com/api/character/706',
      'https://rickandmortyapi.com/api/character/707',
      'https://rickandmortyapi.com/api/character/708',
      'https://rickandmortyapi.com/api/character/710',
      'https://rickandmortyapi.com/api/character/712',
      'https://rickandmortyapi.com/api/character/713',
      'https://rickandmortyapi.com/api/character/714',
      'https://rickandmortyapi.com/api/character/715',
      'https://rickandmortyapi.com/api/character/716',
      'https://rickandmortyapi.com/api/character/717',
      'https://rickandmortyapi.com/api/character/719',
      'https://rickandmortyapi.com/api/character/720',
      'https://rickandmortyapi.com/api/character/721',
      'https://rickandmortyapi.com/api/character/722',
      'https://rickandmortyapi.com/api/character/723',
      'https://rickandmortyapi.com/api/character/724',
      'https://rickandmortyapi.com/api/character/725',
      'https://rickandmortyapi.com/api/character/726',
      'https://rickandmortyapi.com/api/character/727',
      'https://rickandmortyapi.com/api/character/728',
      'https://rickandmortyapi.com/api/character/729',
      'https://rickandmortyapi.com/api/character/730',
      'https://rickandmortyapi.com/api/character/732',
      'https://rickandmortyapi.com/api/character/733',
      'https://rickandmortyapi.com/api/character/734',
      'https://rickandmortyapi.com/api/character/735',
      'https://rickandmortyapi.com/api/character/737',
      'https://rickandmortyapi.com/api/character/738',
      'https://rickandmortyapi.com/api/character/739',
      'https://rickandmortyapi.com/api/character/740',
      'https://rickandmortyapi.com/api/character/741',
      'https://rickandmortyapi.com/api/character/742',
      'https://rickandmortyapi.com/api/character/753',
      'https://rickandmortyapi.com/api/character/754',
      'https://rickandmortyapi.com/api/character/755',
      'https://rickandmortyapi.com/api/character/756',
      'https://rickandmortyapi.com/api/character/757',
      'https://rickandmortyapi.com/api/character/758',
      'https://rickandmortyapi.com/api/character/759',
      'https://rickandmortyapi.com/api/character/760',
      'https://rickandmortyapi.com/api/character/761',
      'https://rickandmortyapi.com/api/character/762',
      'https://rickandmortyapi.com/api/character/763',
      'https://rickandmortyapi.com/api/character/764',
      'https://rickandmortyapi.com/api/character/765',
      'https://rickandmortyapi.com/api/character/766',
      'https://rickandmortyapi.com/api/character/767',
      'https://rickandmortyapi.com/api/character/768',
      'https://rickandmortyapi.com/api/character/769',
      'https://rickandmortyapi.com/api/character/770',
      'https://rickandmortyapi.com/api/character/771',
      'https://rickandmortyapi.com/api/character/772',
      'https://rickandmortyapi.com/api/character/773',
      'https://rickandmortyapi.com/api/character/774',
      'https://rickandmortyapi.com/api/character/775',
      'https://rickandmortyapi.com/api/character/776',
      'https://rickandmortyapi.com/api/character/777',
      'https://rickandmortyapi.com/api/character/778',
      'https://rickandmortyapi.com/api/character/781',
      'https://rickandmortyapi.com/api/character/786',
      'https://rickandmortyapi.com/api/character/788',
      'https://rickandmortyapi.com/api/character/789',
      'https://rickandmortyapi.com/api/character/790',
      'https://rickandmortyapi.com/api/character/791',
      'https://rickandmortyapi.com/api/character/203',
      'https://rickandmortyapi.com/api/character/794',
      'https://rickandmortyapi.com/api/character/800',
      'https://rickandmortyapi.com/api/character/813',
      'https://rickandmortyapi.com/api/character/821',
      'https://rickandmortyapi.com/api/character/826',
    ],
    url: 'https://rickandmortyapi.com/api/location/20',
    created: '2017-11-18T19:33:01.173Z',
  },
  {
    id: 21,
    name: 'Testicle Monster Dimension',
    type: 'Dimension',
    dimension: 'Testicle Monster Dimension',
    residents: ['https://rickandmortyapi.com/api/character/7', 'https://rickandmortyapi.com/api/character/436'],
    url: 'https://rickandmortyapi.com/api/location/21',
    created: '2017-11-18T19:41:01.605Z',
  },
];
